In [8]:
import pandas as pd
a = pd.Series([1,2,3,4,5] , index=['a','b','c','d','e'])
a

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [17]:
student = {
    "name": "Alice",
    "age": 20,
    "grade": "A",
    "city": "Pune"
}
b = pd.Series(student)
print(b)

name     Alice
age         20
grade        A
city      Pune
dtype: object

In [14]:
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

15
1
5
3.0

In [15]:
a[a>2]

c    3
d    4
e    5
dtype: int64

In [16]:
a.drop('a')

b    2
c    3
d    4
e    5
dtype: int64

In [19]:
a['a'] = 1
print(a)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [20]:
a['f'] = 6
print(a)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [25]:
import pandas as pd

fruits = [
    "Apple", "Banana", "Orange", "Mango", "Grapes",
    "Pineapple", "Strawberry", "Watermelon", "Papaya", "Kiwi"
]

df = pd.DataFrame(fruits)
df

            0
0       Apple
1      Banana
2      Orange
3       Mango
4      Grapes
5   Pineapple
6  Strawberry
7  Watermelon
8      Papaya
9        Kiwi

In [27]:
data = [{'name': 'Alice', 'age': 20, 'grade': 'A', 'city': 'Pune'},{'name': 'Ana', 'age': 21, 'grade': 'B', 'city': 'Pune'},{'name': 'Nick', 'age': 22, 'grade': 'c', 'city': 'Pune'}]
df2 = pd.DataFrame(data)
df2

    name  age grade  city
0  Alice   20     A  Pune
1    Ana   21     B  Pune
2   Nick   22     c  Pune

In [ ]:
df = pd.read_csv(')